version: '2' 

services:

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "/var/lib/grafana:/var/lib/grafana"

  influxdb:
    image: influxdb 
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "/var/lib/influxdb:/var/lib/influxdb"

