version: '2' 

services:

  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "/var/lib/grafana:/var/lib/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
        #- GF_SECURITY_ADMIN_USER=false

  influxdb:
    restart: always
    image: influxdb 
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - "/var/lib/influxdb:/var/lib/influxdb"

